@testable import aoc
import Testing

struct Day7Tests {

    let input = """
    .......S.......
    ...............
    .......^.......
    ...............
    ......^.^......
    ...............
    .....^.^.^.....
    ...............
    ....^.^...^....
    ...............
    ...^.^...^.^...
    ...............
    ..^...^.....^..
    ...............
    .^.^.^.^.^...^.
    ...............
    """

    @Test func testPart1() {
        let day = Day7(input: input)
        #expect(day.answerPart1() == 21)
    }

    @Test func testPart2() {
        let day = Day7(input: input)
        #expect(day.answerPart2() == 40)
    }
}
